
import React from 'react'

const AboutUs = () => {
    return (
        <div className="container">
            <div className="py-4">
                <h1>About Us</h1>
                <p className="leade">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Piso igitur hoc modo, vir optimus tuique, ut scis, amantissimus. Quod, inquit, quamquam voluptatibus quibusdam est saepe iucundius, tamen expetitur propter voluptatem. Ac tamen, ne cui loco non videatur esse responsum, pauca etiam nunc dicam ad reliquam orationem tuam. Ita ceterorum sententiis semotis relinquitur non mihi cum Torquato, sed virtuti cum voluptate certatio. Huc et illuc, Torquate, vos versetis licet, nihil in hac praeclara epistula scriptum ab Epicuro congruens et conveniens decretis eius reperietis. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Duo Reges: constructio interrete. Memini vero, inquam; Alii rursum isdem a principiis omne officium referent aut ad voluptatem aut ad non dolendum aut ad prima illa secundum naturam optinenda. Addo etiam illud, multa iam mihi dare signa puerum et pudoris et ingenii, sed aetatem vides.
                    Sed quamvis comis in amicis tuendis fuerit, tamen, si haec vera sunt-nihil enim affirmo-, non satis acutus fuit. Sin eam, quam Hieronymus, ne fecisset idem, ut voluptatem illam Aristippi in prima commendatione poneret. Aliter homines, aliter philosophos loqui putas oportere? Ita fit beatae vitae domina fortuna, quam Epicurus ait exiguam intervenire sapienti. Et quidem saepe quaerimus verbum Latinum par Graeco et quod idem valeat; Non ego tecum iam ita iocabor, ut isdem his de rebus, cum L. Curium putes loqui, interdum ita laudat, ut quid praeterea sit bonum neget se posse ne suspicari quidem. Fortitudinis quaedam praecepta sunt ac paene leges, quae effeminari virum vetant in dolore. Res enim se praeclare habebat, et quidem in utraque parte. Sed tamen omne, quod de re bona dilucide dicitur, mihi praeclare dici videtur.
                    Etsi ea quidem, quae adhuc dixisti, quamvis ad aetatem recte isto modo dicerentur. Qui bonum omne in virtute ponit, is potest dicere perfici beatam vitam perfectione virtutis; Et quae per vim oblatum stuprum volontaria morte lueret inventa est et qui interficeret filiam, ne stupraretur. Nihilne te delectat umquam -video, quicum loquar-, te igitur, Torquate, ipsum per se nihil delectat? Sed tamen omne, quod de re bona dilucide dicitur, mihi praeclare dici videtur. Addebat etiam se in legem Voconiam iuratum contra eam facere non audere, nisi aliter amicis videretur. Potius inflammat, ut coercendi magis quam dedocendi esse videantur. Callipho ad virtutem nihil adiunxit nisi voluptatem, Diodorus vacuitatem doloris. Aut unde est hoc contritum vetustate proverbium: quicum in tenebris?
                    Curium putes loqui, interdum ita laudat, ut quid praeterea sit bonum neget se posse ne suspicari quidem. Sed in ceteris artibus cum dicitur artificiose, posterum quodam modo et consequens putandum est, quod illi §pigennhmatikÒn appellant; Quo studio Aristophanem putamus aetatem in litteris duxisse? Si sapiens, ne tum quidem miser, cum ab Oroete, praetore Darei, in crucem actus est. Atqui perspicuum est hominem e corpore animoque constare, cum primae sint animi partes, secundae corporis. Tecum optime, deinde etiam cum mediocri amico. Bonum integritas corporis: misera debilitas. Atque haec ita iustitiae propria sunt, ut sint virtutum reliquarum communia. Deque his rebus satis multa in nostris de re publica libris sunt dicta a Laelio. Quae etsi mihi nullo modo probantur, tamen Democritum laudatum a ceteris ab hoc, qui eum unum secutus esset, nollem vituperatum. Quia dolori non voluptas contraria est, sed doloris privatio. Res tota, Torquate, non doctorum hominum, velle post mortem epulis celebrari memoriam sui nominis. His singulis copiose responderi solet, sed quae perspicua sunt longa esse non debent. Virtutibus igitur rectissime mihi videris et ad consuetudinem nostrae orationis vitia posuisse contraria.
                </p>
                <p className="leade">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Piso igitur hoc modo, vir optimus tuique, ut scis, amantissimus. Quod, inquit, quamquam voluptatibus quibusdam est saepe iucundius, tamen expetitur propter voluptatem. Ac tamen, ne cui loco non videatur esse responsum, pauca etiam nunc dicam ad reliquam orationem tuam. Ita ceterorum sententiis semotis relinquitur non mihi cum Torquato, sed virtuti cum voluptate certatio. Huc et illuc, Torquate, vos versetis licet, nihil in hac praeclara epistula scriptum ab Epicuro congruens et conveniens decretis eius reperietis. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Duo Reges: constructio interrete. Memini vero, inquam; Alii rursum isdem a principiis omne officium referent aut ad voluptatem aut ad non dolendum aut ad prima illa secundum naturam optinenda. Addo etiam illud, multa iam mihi dare signa puerum et pudoris et ingenii, sed aetatem vides.
                    Sed quamvis comis in amicis tuendis fuerit, tamen, si haec vera sunt-nihil enim affirmo-, non satis acutus fuit. Sin eam, quam Hieronymus, ne fecisset idem, ut voluptatem illam Aristippi in prima commendatione poneret. Aliter homines, aliter philosophos loqui putas oportere? Ita fit beatae vitae domina fortuna, quam Epicurus ait exiguam intervenire sapienti. Et quidem saepe quaerimus verbum Latinum par Graeco et quod idem valeat; Non ego tecum iam ita iocabor, ut isdem his de rebus, cum L. Curium putes loqui, interdum ita laudat, ut quid praeterea sit bonum neget se posse ne suspicari quidem. Fortitudinis quaedam praecepta sunt ac paene leges, quae effeminari virum vetant in dolore. Res enim se praeclare habebat, et quidem in utraque parte. Sed tamen omne, quod de re bona dilucide dicitur, mihi praeclare dici videtur.
                    Etsi ea quidem, quae adhuc dixisti, quamvis ad aetatem recte isto modo dicerentur. Qui bonum omne in virtute ponit, is potest dicere perfici beatam vitam perfectione virtutis; Et quae per vim oblatum stuprum volontaria morte lueret inventa est et qui interficeret filiam, ne stupraretur. Nihilne te delectat umquam -video, quicum loquar-, te igitur, Torquate, ipsum per se nihil delectat? Sed tamen omne, quod de re bona dilucide dicitur, mihi praeclare dici videtur. Addebat etiam se in legem Voconiam iuratum contra eam facere non audere, nisi aliter amicis videretur. Potius inflammat, ut coercendi magis quam dedocendi esse videantur. Callipho ad virtutem nihil adiunxit nisi voluptatem, Diodorus vacuitatem doloris. Aut unde est hoc contritum vetustate proverbium: quicum in tenebris?
                    Curium putes loqui, interdum ita laudat, ut quid praeterea sit bonum neget se posse ne suspicari quidem. Sed in ceteris artibus cum dicitur artificiose, posterum quodam modo et consequens putandum est, quod illi §pigennhmatikÒn appellant; Quo studio Aristophanem putamus aetatem in litteris duxisse? Si sapiens, ne tum quidem miser, cum ab Oroete, praetore Darei, in crucem actus est. Atqui perspicuum est hominem e corpore animoque constare, cum primae sint animi partes, secundae corporis. Tecum optime, deinde etiam cum mediocri amico. Bonum integritas corporis: misera debilitas. Atque haec ita iustitiae propria sunt, ut sint virtutum reliquarum communia. Deque his rebus satis multa in nostris de re publica libris sunt dicta a Laelio. Quae etsi mihi nullo modo probantur, tamen Democritum laudatum a ceteris ab hoc, qui eum unum secutus esset, nollem vituperatum. Quia dolori non voluptas contraria est, sed doloris privatio. Res tota, Torquate, non doctorum hominum, velle post mortem epulis celebrari memoriam sui nominis. His singulis copiose responderi solet, sed quae perspicua sunt longa esse non debent. Virtutibus igitur rectissime mihi videris et ad consuetudinem nostrae orationis vitia posuisse contraria.
                </p>
                <p className="leade">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Piso igitur hoc modo, vir optimus tuique, ut scis, amantissimus. Quod, inquit, quamquam voluptatibus quibusdam est saepe iucundius, tamen expetitur propter voluptatem. Ac tamen, ne cui loco non videatur esse responsum, pauca etiam nunc dicam ad reliquam orationem tuam. Ita ceterorum sententiis semotis relinquitur non mihi cum Torquato, sed virtuti cum voluptate certatio. Huc et illuc, Torquate, vos versetis licet, nihil in hac praeclara epistula scriptum ab Epicuro congruens et conveniens decretis eius reperietis. Hic Speusippus, hic Xenocrates, hic eius auditor Polemo, cuius illa ipsa sessio fuit, quam videmus. Duo Reges: constructio interrete. Memini vero, inquam; Alii rursum isdem a principiis omne officium referent aut ad voluptatem aut ad non dolendum aut ad prima illa secundum naturam optinenda. Addo etiam illud, multa iam mihi dare signa puerum et pudoris et ingenii, sed aetatem vides.
                    Sed quamvis comis in amicis tuendis fuerit, tamen, si haec vera sunt-nihil enim affirmo-, non satis acutus fuit. Sin eam, quam Hieronymus, ne fecisset idem, ut voluptatem illam Aristippi in prima commendatione poneret. Aliter homines, aliter philosophos loqui putas oportere? Ita fit beatae vitae domina fortuna, quam Epicurus ait exiguam intervenire sapienti. Et quidem saepe quaerimus verbum Latinum par Graeco et quod idem valeat; Non ego tecum iam ita iocabor, ut isdem his de rebus, cum L. Curium putes loqui, interdum ita laudat, ut quid praeterea sit bonum neget se posse ne suspicari quidem. Fortitudinis quaedam praecepta sunt ac paene leges, quae effeminari virum vetant in dolore. Res enim se praeclare habebat, et quidem in utraque parte. Sed tamen omne, quod de re bona dilucide dicitur, mihi praeclare dici videtur.
                    Etsi ea quidem, quae adhuc dixisti, quamvis ad aetatem recte isto modo dicerentur. Qui bonum omne in virtute ponit, is potest dicere perfici beatam vitam perfectione virtutis; Et quae per vim oblatum stuprum volontaria morte lueret inventa est et qui interficeret filiam, ne stupraretur. Nihilne te delectat umquam -video, quicum loquar-, te igitur, Torquate, ipsum per se nihil delectat? Sed tamen omne, quod de re bona dilucide dicitur, mihi praeclare dici videtur. Addebat etiam se in legem Voconiam iuratum contra eam facere non audere, nisi aliter amicis videretur. Potius inflammat, ut coercendi magis quam dedocendi esse videantur. Callipho ad virtutem nihil adiunxit nisi voluptatem, Diodorus vacuitatem doloris. Aut unde est hoc contritum vetustate proverbium: quicum in tenebris?
                    Curium putes loqui, interdum ita laudat, ut quid praeterea sit bonum neget se posse ne suspicari quidem. Sed in ceteris artibus cum dicitur artificiose, posterum quodam modo et consequens putandum est, quod illi §pigennhmatikÒn appellant; Quo studio Aristophanem putamus aetatem in litteris duxisse? Si sapiens, ne tum quidem miser, cum ab Oroete, praetore Darei, in crucem actus est. Atqui perspicuum est hominem e corpore animoque constare, cum primae sint animi partes, secundae corporis. Tecum optime, deinde etiam cum mediocri amico. Bonum integritas corporis: misera debilitas. Atque haec ita iustitiae propria sunt, ut sint virtutum reliquarum communia. Deque his rebus satis multa in nostris de re publica libris sunt dicta a Laelio. Quae etsi mihi nullo modo probantur, tamen Democritum laudatum a ceteris ab hoc, qui eum unum secutus esset, nollem vituperatum. Quia dolori non voluptas contraria est, sed doloris privatio. Res tota, Torquate, non doctorum hominum, velle post mortem epulis celebrari memoriam sui nominis. His singulis copiose responderi solet, sed quae perspicua sunt longa esse non debent. Virtutibus igitur rectissime mihi videris et ad consuetudinem nostrae orationis vitia posuisse contraria.
                </p>
            </div>
        </div>
    )
}

export default AboutUs;
